# for Plane navigation
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# for Window navigation
bind -n M-u choose-tree
bind -n M-x kill-window
bind -n M-Space  next-layout

# Active pane highlight
set -g pane-active-border-style fg=green

# Inactive pane border
set -g pane-border-style fg=gray

# Show pane number on border
set -g pane-border-status top
set -g pane-border-format " #P "

# adding space in border
set -g pane-border-lines single
